id: P5ED9D3B0
initial_creation_type: ocr
source_metadata:
  volumes:
    b1d4ca8e2fde45a08aa5f2827da0e1f0:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: བྱང་ཆུབ་སེམས་དཔའི་ཚུལ་ཁྲིམས་ཀྱི་ལེའུའི་བཤད་པ།
      total_pages: 1529
      volume_number: 75
