id: D313B0E40
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-28T06:18:33+00:00'
last_modified: '2022-05-29T08:21:12.564252+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    dda6:
      image_group_id: I1PD95920
      title: བྱང་ཆུབ་སེམས་དཔའི་ཚུལ་ཁྲིམས་ཀྱི་ལེའུའི་བཤད་པ།
      total_pages: 1529
      order: 75
      base_file: dda6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
